version: 2

build:
  os: ubuntu-lts-latest
  tools:
    python: "3.11"
  commands:
    - python -m pip install --upgrade pip
    - python -m pip install mkdocs-material
    - python -m pip install -e .
    - python -m mkdocs build -d $READTHEDOCS_OUTPUT/html

mkdocs:
  configuration: mkdocs.yml