site_name: ncorn
site_description: Production-ready ASGI web server for FastAPI applications
site_url: https://ncorn.readthedocs.io/
repo_name: ndugram/ncorn
repo_url: https://github.com/ndugram/ncorn
edit_uri: edit/main/docs/

strict: true

theme:
  name: material
  logo: logo.png
  favicon: logo.png

  palette:
    - scheme: "default"
      media: "(prefers-color-scheme: light)"
      toggle:
        icon: "material/lightbulb"
        name: "Switch to dark mode"
    - scheme: "slate"
      media: "(prefers-color-scheme: dark)"
      primary: "deep orange"
      accent: "orange"
      toggle:
        icon: "material/lightbulb-outline"
        name: "Switch to light mode"

  icon:
    repo: fontawesome/brands/github

  features:
    - content.code.annotate
    - content.code.copy
    - content.tabs.link
    - navigation.footer
    - navigation.path
    - navigation.sections
    - navigation.top
    - navigation.tracking
    - search.suggest
    - search.highlight
    - toc.follow

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/ndugram/ncorn
    - icon: fontawesome/brands/discord
      link: https://discord.gg/ncorn
    - icon: fontawesome/brands/twitter
      link: https://x.com/ncorn_dev

  alternate:
    - link: /
      name: English
    - link: /ru/
      name: Russian

markdown_extensions:
  - attr_list
  - admonition
  - codehilite:
      css_class: highlight
  - toc:
      permalink: true
  - pymdownx.details
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.extra:

plugins:
  - search

nav:
  - Welcome: 
    - en: en/index.md
    - ru: ru/index.md
  - Installation:
    - en: en/installation.md
    - ru: ru/installation.md
  - Settings:
    - en: en/settings.md
    - ru: ru/settings.md
  - Server Behavior:
    - en: en/server-behavior.md
    - ru: ru/server-behavior.md
  - Concepts:
    - en: en/concepts/asgi.md
    - ru: ru/concepts/asgi.md
    - Lifespan:
      - en: en/concepts/lifespan.md
      - ru: ru/concepts/lifespan.md
    - WebSockets:
      - en: en/concepts/websockets.md
      - ru: ru/concepts/websockets.md
  - Deployment:
    - Deployment:
      - en: en/deployment/index.md
      - ru: ru/deployment/index.md
    - Docker:
      - en: en/deployment/docker.md
      - ru: ru/deployment/docker.md
  - API Reference:
    - en: en/api-reference.md
    - ru: ru/api-reference.md
  - Contributing:
    - en: en/contributing.md
    - ru: ru/contributing.md
